Revert "Bump .NET SDK from 5.0 to 6.0"
This reverts commit db4b796eda315e709f1d2244893696dc3ed8de45 since CI
was picking up test failures when running the move-prover test suite:

```
test prover unit[simplify]::functional/unused_schema.move ... FAILED
Error: cannot extract version from `/opt/dotnet/tools/boogie`
```

Closes: #9995