[CI][easy] fix code coverage report script
We worked around Cargo's feature unification so that we can separate
testing and fuzzing code (99183107 [build]).  But the original
`cargo test` is not able to run the tests on a crate. We need to pass
`--all-feature` option as well.

This fixes the following error when running the coverage report script
```
error[E0433]: failed to resolve: could not find `test_helpers` in `libra_types`
```

Closes: #1523
Approved by: huitseeker