[smoke tests] fix flaky node panic due to rebuild in parallel tests (#5308)
### Description

With smoke tests running in parallel, some tests failed on node panic after asserting that feature "testing" from crate move-stdlib is set.

```
thread 'main' panicked at 'assertion failed: aptos_natives(NativeGasParameters::zeros(),\n            AbstractValueSizeGasParameters::zeros(),\n            LATEST_GAS_FEATURE_VERSION).into_iter().all(|(_, module_name,\n            func_name, _)|\n        module_name.as_str() != \"unit_test\" &&\n            func_name.as_str() != \"create_signers_for_testing\")', aptos-move/aptos-vm/src/natives.rs:55:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is because other tests that call `get_bin` were recompiling aptos-node without release flags. So there is a race where a node is startup with the non-release aptos-node.

We don't actually need a non-release version for smoke tests. So removing that completely and adding some sharing to prevent the builds from diverging again.

### Test Plan

Add an explicit deterministic repro that failed before this fix.